sudo: required
dist: trusty

language: node_js
node_js:
    - "4"

env:
    global:
        - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949

matrix:
    include:
        - node_js: "4"
env: TEST_SUITE=lint

branches:
    except:
        - /^greenkeeper-.+$/

cache:
    yarn: true
    directories:
        - node_modules

addons:
    firefox: "latest"
apt:
    sources:
        - google-chrome
packages:
    - google-chrome-stable

before_install:

install:
  - npm i -g yarn
  - yarn global add bower
  - yarn install
  - bower install
before_script:
    - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3;

script:
    - yarn test
